export const HITS = 'Aciertos'
export const TURNS = 'Turnos'
export const CHARACTERS = 'Personajes'
export const PAGE_TITLE = 'Juego de Memoria'
export const CONGRATS = '¡Felicitaciones!'
export const FINISHED_TEXT = 'Terminaste el juego con '
